#!/usr/bin/env bash
# 4 bad luck, 8 is your chance

n=1
while [ $n -le 10 ]
do
	if [ $n -eq 4 ]
	then
		echo "bad luck"
	elif [ $n -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$(( n+1 ))
done
